# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alessandro/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.srcs/sources_1/ip/tanh_lut/tanh_lut.xci
# IP: The module: 'tanh_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.gen/sources_1/ip/tanh_lut/tanh_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_lut'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alessandro/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.srcs/sources_1/ip/tanh_lut/tanh_lut.xci
# IP: The module: 'tanh_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.gen/sources_1/ip/tanh_lut/tanh_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
