# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aleva/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.srcs/sources_1/ip/x_RAM/x_RAM.xci
# IP: The module: 'x_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aleva/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.gen/sources_1/ip/x_RAM/x_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/aleva/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.srcs/sources_1/ip/x_RAM/x_RAM.xci
# IP: The module: 'x_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aleva/OneDrive/Documenti/Politecnico/Dottorato/Progetti/Vivado/DUAL-LSTM/HLSTM.gen/sources_1/ip/x_RAM/x_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
